//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tabuleiro
{
    using System;
    using System.Collections.Generic;
    
    public partial class Carta
    {
        public int idCarta { get; set; }
        public string Nome { get; set; }
        public string Tipo { get; set; }
        public string NomeArquivoImagem { get; set; }
        public string TipoImagem { get; set; }
        public Nullable<int> ZonaId { get; set; }
    
        public virtual Zona Zona { get; set; }
    }
}
